# Use postgres/123456 user/password credentials
version: '3.1'

services:
  webapp:
    build: .  
    # image: thinh1611/public-note:v1.0
    ports:
      - 8081:8080
    command: npm start
    environment:
      - NODE_ENV=production
    container_name: public-note